[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "gen-async-await-macros"
publish = false
version = "0.0.0-alpha.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
quote = "1.0.2"

[dependencies.syn]
features = ["full"]
version = "1.0.11"