[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
edition = "2018"
name = "alloc-oom"
publish = false
version = "0.0.0-alpha.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloc-oom-macros = { path = "macros" }
